"""Lightweight SysML v2 parser used for validation and metrics."""

from __future__ import annotations

import re
from typing import Any


class SysMLv2Parser:
    """Parse a constrained SysML v2 subset generated by this pipeline."""

    _BLOCK_RE = re.compile(r"\bblock\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{")
    _PART_RE = re.compile(r"\bpart\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([A-Za-z_][A-Za-z0-9_]*)\s*;")
    _ATTR_RE = re.compile(
        r"\battribute\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;]+);"
    )
    _CONNECT_RE = re.compile(r"\bconnect\s+([^\s]+)\s+to\s+([^;\s]+)\s*;")
    _CONSTRAINT_RE = re.compile(r"\bconstraint\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([^;]+);")

    def parse(self, sysml_code: str) -> Any:
        block_match = self._BLOCK_RE.search(sysml_code)
        model_name = block_match.group(1) if block_match else "UnknownModel"

        components = []
        for name, ctype in self._PART_RE.findall(sysml_code):
            components.append({"name": name, "type": ctype})

        parameters = []
        for name, ptype, value in self._ATTR_RE.findall(sysml_code):
            parameters.append({"name": name, "type": ptype, "value": value.strip()})

        connections = []
        for src, dst in self._CONNECT_RE.findall(sysml_code):
            connections.append({"from": src, "to": dst})

        constraints = []
        for name, expression in self._CONSTRAINT_RE.findall(sysml_code):
            constraints.append({"name": name, "expression": expression.strip()})

        return {
            "model_name": model_name,
            "components": components,
            "parameters": parameters,
            "connections": connections,
            "constraints": constraints,
        }
